# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US
    sylius_refund.refund_enum_type: App\Entity\Refund\Type\RefundEnumType
    sylius_refund.refund_type: App\Entity\Refund\RefundType

services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false

    # Makes classes in src/ available to be used as services;
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    #######################
    # Configure OrderItem #
    #######################
    App\Converter\RequestToOrderItemRefundConverter:
        arguments:
            - '@Sylius\RefundPlugin\Converter\RefundUnitsConverterInterface'
        tags: ['sylius_refund.request_to_refund_units_converter']

    App\Converter\OrderItemLineItemsConverter:
        arguments:
            - '@sylius.repository.order_item'
            - '@Sylius\RefundPlugin\Provider\TaxRateProviderInterface'
        tags: ['sylius_refund.line_item_converter']

    App\Provider\OrderItemTotalProvider:
        arguments:
            - '@sylius.repository.order_item'
        tags: [{ name: 'sylius_refund.refund_unit_total_provider', refund_type: 'order_item' }]
    
    App\Refunder\OrderItemsRefunder:
        arguments:
            - '@Sylius\RefundPlugin\Creator\RefundCreatorInterface'
            - '@sylius.event_bus'
            - '@Sylius\RefundPlugin\Filter\UnitRefundFilterInterface'
        tags: ['sylius_refund.refunder']
    
    App\Listener\ItemRefundedEventListener:
        arguments:
            - '@Sylius\RefundPlugin\StateResolver\OrderPartiallyRefundedStateResolverInterface'
        tags: [{ name: 'messenger.message_handler', bus: 'sylius.event_bus' }]
        
    #########################    
    # Disable OrderItemUnit #
    #########################
    Sylius\RefundPlugin\Converter\OrderItemUnitLineItemsConverter:
        tags: []

    Sylius\RefundPlugin\Converter\RequestToOrderItemUnitRefundConverter:
        tags: []
    
    Sylius\RefundPlugin\Refunder\OrderItemUnitsRefunder:
        tags: []
